graph TD
__start__["开始"]
    reception["reception"]
    sql_agent["sql_agent"]
    rag_agent["rag_agent"]
    code_agent["code_agent"]
    __end__["结束"]
    __start__ --> reception
    reception -.-> code_agent
    reception -.-> rag_agent
    reception -.-> sql_agent
    code_agent --> __end__
    rag_agent --> __end__
    sql_agent --> __end__
